config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :flights

  resources :bookings

  resources :passengers, only: [ "new", "create" ]

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: "departure_airport_id", class_name: "Flight"
  has_many :arriving_flights, foreign_key: "arrival_airport_id", class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, foreign_key: "departure_airport_id", class_name: "Airport"
  belongs_to :arrival_airport, foreign_key: "arrival_airport_id", class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings

  def format_departure_date
    self.departure_date.strftime("%A, %B %d, %Y")
  end

  def departure_date_to_date
    self.departure_date.to_date
  end

  def self.distinct_days
    flights_distinct_days = []
    Flight.all.each do |f|
      flights_distinct_days.push(f) unless flights_distinct_days.any? { |added_flight| added_flight.departure_date.to_date == f.departure_date.to_date }
    end
    flights_distinct_days
  end

  def format_flight_radio_label
    "Flight ##{self.id}: #{self.departure_airport.code} → #{self.arrival_airport.code} Duration: #{self.duration_hrs} hour(s) "
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    @passenger_count = params[:passenger_count].to_i
    @passenger_count.times do
      @passenger = @booking.passengers.build
    end
  end

  def create
    @booking = Booking.new(booking_params)

    if @booking.save!
      @booking.passengers.each do |p|
        PassengerMailer.with(user: p).confirmation_email.deliver_now!
      end
      redirect_to @booking
    else
      redirect_to root_path
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.expect(booking: [ :flight_id, passengers_attributes: [ [ :name, :email ] ] ])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
    if params[:departure_airport].present?
      @flight_search_results = Flight.where("departure_airport_id = ? AND arrival_airport_id = ? AND departure_date LIKE ?",
         params[:departure_airport], params[:arrival_airport], params[:departure_date] + "%")
    end
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  def new
    @passenger = Passenger.new
  end

  def create
    @passenger = Passenger.new(passenger_params)

    @passenger.save
  end

  private

  def passenger_params
    params.expect(passenger: [ :name, :email ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/bookings/new.html.erb
<h1>Flight #<%= @flight.id %> Booking Form</h1>

<%= form_with model: @booking do |f| %>

    <div>
        <%= f.hidden_field :flight_id, value: @flight.id %>
    </div>

    <div>
        <%= f.label :flight, "Flight #: #"%>
        <%= f.collection_select :flight, Flight.all, :id, :id, { selected: @flight.id }, disabled: "true"%>
    </div><br/>

    <div>
        <%= f.label :departure_airport, "Depart from: "%>
        <%= f.collection_select :departure_airport, Airport.all, :id, :code, { selected: @flight.departure_airport.id },  disabled: "true"%>
    </div><br/>

    <div>
        <%= f.label :arrival_airport, "Arrive at: "%>
        <%= f.collection_select :arrival_airport, Airport.all, :id, :code, { selected: @flight.arrival_airport.id },  disabled: "true"%>
    </div><br/>

    <div>
        <%= f.label :departure_date, "Departure date: "%>
        <%= f.collection_select :departure_date, Flight.all, :departure_date, "format_departure_date", { selected: @flight.departure_date },  disabled: "true"%>
    </div><br/>

    <div data-controller="passenger">
        <ol data-passenger-target="passengerList" style="display: flex; flex-direction: column; gap: 20px;">
            <%= f.fields_for :passengers do |sub_form| %>
                <li>
                    <div style="display: flex; gap: 5px;">
                        <%= sub_form.label :name, "Name: " %>
                        <%= sub_form.text_field :name %>

                        <%= sub_form.label :email, "E-mail: " %>
                        <%= sub_form.text_field :email %>

                        <button class="remove-passenger-button"  type="button" data-passenger-target="removePassengerButton" data-action="click->passenger#removePassenger">- Remove Passenger</button>
                    </div>
                </li>
            <% end %>
        </ol>

        <div>
            <template data-passenger-target="template">
                <%= f.fields_for 'passengers_attributes[]', Passenger.new, index: "__INDEX__" do |sub_form| %>
                    <li>
                        <div style="display: flex; gap: 5px;">
                            <%= sub_form.label :name, "Name:" %>
                            <%= sub_form.text_field :name %>
                        
                            <%= sub_form.label :email, "E-mail: " %>
                            <%= sub_form.text_field :email %>

                            <button class="remove-passenger-button" type="button" data-passenger-target="removePassengerButton" data-action="click->passenger#removePassenger">- Remove Passenger</button>
                        </div>
                    </li>
                <% end %>
            </template>
        </div>

        <div>
            <button type="button" data-passenger-target="addPassengerButton" data-action="click->passenger#addPassenger">Add Passenger</button>
        </div>
    </div>

    <div>
        <%= f.submit "Book" %>
    </div>

<% end %>

app/views/bookings/show.html.erb
<h1>Booking #<%= @booking.id %></h1>

<h2>Flight Information</h2>

<p>Flight #: #<%= @booking.flight_id %></p>

<p>Departure date: <%= @booking.flight.format_departure_date%>

<p>Departing from: <%= @booking.flight.departure_airport.code %></p>

<p>Arriving at: <%= @booking.flight.arrival_airport.code %></p>

<p>Duration: ~<%= @booking.flight.duration_hrs %>hr(s)</p>

<h2>Passenger Information</h2>

<ol>
    <% @booking.passengers.each do |passenger| %>
        <li>
            <ul>
                <li>
                    <p>Name: <%= passenger.name %></p>
                </li>
                <li>E-mail: <%= passenger.email %></li>
            </ul>
        </li>
    <% end %>
</ol>

app/views/flights/index.html.erb
<h1>Flight Booker</h1>

<h2>Flight Search</h2>

<%= form_with url: root_path, method: "GET" do |f| %>

    <div>
        <%= f.label :departure_airport, "Depart From:"%>
        <%= f.collection_select(:departure_airport, Airport.all, :id, :code, selected: params[:departure_airport]) %>
    </div><br/>

    <div>
        <%= f.label :arrival_airport, "Arrive At:"%>
        <%= f.collection_select(:arrival_airport, Airport.all, :id, :code, selected: params[:arrival_airport]) %>
    </div><br/>

    <div>
        <%= f.label :passenger_count, "Passengers:"%>
        <%= f.select(:passenger_count, 1..4, selected: params[:passenger_count]) %>
    </div><br/>

    <div>
        <%= f.label :departure_date, "Departure Date:"%>
        <%= f.collection_select(:departure_date, Flight.distinct_days.sort_by { |flight| flight.departure_date}, "departure_date_to_date", "format_departure_date", selected: params[:departure_date]) %>
    </div><br/>

    <div>
        <%= f.submit "Search" %>
    </div>

<% end %>

<% if params[:departure_airport].present? && @flight_search_results.present? %>
    <h2>Found Flights:</h2>
    <%= form_with url: new_booking_path , method: "GET" do |f| %>

        <div>
            <%= f.collection_radio_buttons :flight_id, @flight_search_results, :id, "format_flight_radio_label" %>
        </div><br/>

        <div>
            <%= f.hidden_field :passenger_count, value: params[:passenger_count] %>
        </div>

        <div>
            <%= f.submit "Start Booking" %>
        </div>

    <% end %>
<% elsif !params[:departure_airport].nil? && !@flight_search_results.present? %>
    <h2>Found Flights:</h2>
    <p>No flights match the search parameters...</p>
<% else %>
    <p>Begin your flight search by filling out the fields above ⤴</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Flight Booker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>